CREATE TABLE PUBLIC.portfolio
(
    id        VARCHAR(255) NOT NULL,
    name      VARCHAR(255),
    client_id VARCHAR(255),
    CONSTRAINT pk_portfolio PRIMARY KEY (id)
);

CREATE TABLE PUBLIC.position
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isin         VARCHAR(255),
    quantity    DOUBLE PRECISION,
    origin      SMALLINT,
    bank        SMALLINT,
    portfolio_id VARCHAR(255),
    client_id    VARCHAR(255),
    CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE PUBLIC.security
(
    isin VARCHAR(255) NOT NULL,
    name         VARCHAR(255),
    currency     VARCHAR(255),
    market_price DOUBLE PRECISION,
    CONSTRAINT pk_security PRIMARY KEY (isin)
);