CREATE TABLE consolidated_position_entity
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    security_id          BIGINT,
    internal_position_id VARCHAR(255),
    CONSTRAINT pk_consolidated_position_entity PRIMARY KEY (id)
);

CREATE TABLE consolidated_position_entity_bank_positions
(
    consolidated_position_entity_id BIGINT       NOT NULL,
    bank_positions_id               VARCHAR(255) NOT NULL,
    CONSTRAINT pk_consolidated_position_entity_bankpositions PRIMARY KEY (consolidated_position_entity_id, bank_positions_id)
);

CREATE TABLE portfolio_entity
(
    id        VARCHAR(255) NOT NULL,
    name      VARCHAR(255),
    client_id VARCHAR(255),
    CONSTRAINT pk_portfolio_entity PRIMARY KEY (id)
);

CREATE TABLE portfolio_entity_positions
(
    portfolio_entity_id VARCHAR(255) NOT NULL,
    positions_id        BIGINT       NOT NULL,
    CONSTRAINT pk_portfolio_entity_positions PRIMARY KEY (portfolio_entity_id, positions_id)
);

CREATE TABLE position_entity
(
    id          VARCHAR(255) NOT NULL,
    security_id BIGINT,
    quantity    DOUBLE PRECISION,
    origin      SMALLINT,
    bank        SMALLINT,
    CONSTRAINT pk_position_entity PRIMARY KEY (id)
);

CREATE TABLE security_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isin         VARCHAR(255),
    name         VARCHAR(255),
    currency     VARCHAR(255),
    market_price DOUBLE PRECISION,
    CONSTRAINT pk_security_entity PRIMARY KEY (id)
);

ALTER TABLE consolidated_position_entity_bank_positions
    ADD CONSTRAINT uc_consolidated_position_entity_bank_positions_bankpositions UNIQUE (bank_positions_id);

ALTER TABLE portfolio_entity_positions
    ADD CONSTRAINT uc_portfolio_entity_positions_positions UNIQUE (positions_id);

ALTER TABLE consolidated_position_entity
    ADD CONSTRAINT FK_CONSOLIDATED_POSITION_ENTITY_ON_INTERNALPOSITION FOREIGN KEY (internal_position_id) REFERENCES position_entity (id);

ALTER TABLE consolidated_position_entity
    ADD CONSTRAINT FK_CONSOLIDATED_POSITION_ENTITY_ON_SECURITY FOREIGN KEY (security_id) REFERENCES security_entity (id);

ALTER TABLE position_entity
    ADD CONSTRAINT FK_POSITION_ENTITY_ON_SECURITY FOREIGN KEY (security_id) REFERENCES security_entity (id);

ALTER TABLE consolidated_position_entity_bank_positions
    ADD CONSTRAINT fk_conposentbanpos_on_consolidated_position_entity FOREIGN KEY (consolidated_position_entity_id) REFERENCES consolidated_position_entity (id);

ALTER TABLE consolidated_position_entity_bank_positions
    ADD CONSTRAINT fk_conposentbanpos_on_position_entity FOREIGN KEY (bank_positions_id) REFERENCES position_entity (id);

ALTER TABLE portfolio_entity_positions
    ADD CONSTRAINT fk_porentpos_on_consolidated_position_entity FOREIGN KEY (positions_id) REFERENCES consolidated_position_entity (id);

ALTER TABLE portfolio_entity_positions
    ADD CONSTRAINT fk_porentpos_on_portfolio_entity FOREIGN KEY (portfolio_entity_id) REFERENCES portfolio_entity (id);